apiVersion: 'nais.io/v1alpha1'
kind: Application
metadata:
  name: syfosmsak
  namespace: default
  labels:
    team: "teamsykefravr"
spec:
  name: "syfosmjoark"
  image: "repo.adeo.no:5443/syfo/syfosmsak:@@VERSION@@"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 10
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  vault:
    enabled: true
  env:
    - name: OPPRETT_SAK_URL
      value: {{OPPRETT_SAK_URL}}
    - name: DOKMOT_MOTTA_INNGAAENDE_URL
      value: {{DOKMOT_MOTTA_INNGAAENDE_URL}}
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: {{KAFKA_BOOTSTRAP_SERVERS_URL}}
