apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmsak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 5
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1200m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1536Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfosmsak
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/syfosmsak/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  kafka:
    pool: nav-prod
  webproxy: true
  env:
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.nais.adeo.no/rest/journalpostapi/v1/journalpost
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: SYKMELDING_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-sykmelding-vedlegg-bucket-prod
